module.exports = {
  speech: require('../speech/speech.js'),
  follow: require('../follow/follow.js'),
  mine: require('../mine/mine.js'),
  inventory: require('../inventory/inventory.js'),
  attack: require('../attack/attack.js'),
  ai: require('../ai/ai-enhanced.js'),
  commands: require('../commands/commands.js'),
  sleep: require('../sleep/sleep.js'),
  vehicle: require('../vehicle/vehicle.js'),
  gather: require('../gather/gather.js'),
  tunnel: require('../gather/tunnel.js'),
  vision: require('../vision/vision.js'),
  survival: require('../survival/survival.js'),
  crafting: require('../crafting/crafting.js'),
  smartBehavior: require('../smart-behavior/smart-behavior.js'),
  exploration: require('../exploration/exploration.js'),
  strategy: require('../strategy/strategy.js'),
  memory: require('../memory/memory.js')
}
